config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :orders, only: %i[new create] do
    collection do
      post :confirm
      get :complete
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  validates :name, presence: true, length: { maximum: 40 }
  validates :telephone, presence: true, length: { maximum: 11 }, numericality: { only_integer: true }
  validates :delivery_address, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 100 },
                    email_format: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def confirm
    @order = Order.new(order_params)
    return render :new if @order.invalid?
  end

  def create
    @order = Order.new(order_params)
    return render :new if params[:button] == 'back'

    if @order.save
      session[:order_id] = @order.id
      return redirect_to complete_orders_url
    end
    render :confirm
  end

  def complete
    @order = Order.find_by(id: session[:order_id])
    session[:order_id] = nil
    return redirect_to new_order_url if @order.blank?
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :telephone, :delivery_address)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>注文フォーム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/complete.html.erb
<div class="container mt-3 mb-5">
  <h1 class="text-center mb-5">注文完了</h1>

  <div class="text-center mb-5">
    <p><%= @order.name %>様
      <br>
      ご注文ありがとうございました。
      <br>商品の発送までしばらくお待ち下さい。
    </p>
  </div>
</div>

app/views/orders/confirm.html.erb
<div class="container mt-3 mb-5">
  <h1 class="text-center mb-5">注文内容の確認</h1>

  <div class="col-md-6 max-auto mb-5">
    <p>以下の内容でよろしいでしょうか</p>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.name') %>
      </div>
      <%= @order.name %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.email') %>
      </div>
      <%= @order.email %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.telephone') %>
      </div>
      <%= @order.telephone %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.delivery_address') %>
      </div>
      <%= @order.delivery_address %>
    </div>
  </div>

  <%= form_with model: @order, url: orders_path do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :telephone %>
    <%= f.hidden_field :delivery_address %>

    <div class="d-grid col-md-6 mx-auto mb-4">
      <%= f.button "OK", class: "btn btn-lg btn-primary" %>
    </div>
     <div class="d-grid col-md-6 mx-auto">
      <%= f.button "戻る", value: "back", class: "btn btn-lg btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/orders/new.html.erb
<div class="container mt-3 mb-5">
  <h1 class="text-center mb-5">注文フォーム</h1>
  <%= form_with model: @order, url: confirm_orders_path do |f| %>
    <div class="col-mb-6 mx-auto mb-5">
        <div class="mb-3">
          <%= f.label :name, class: "form-label border-start border-primary border-4 ps-1" %>
          <%= f.text_field :name, size: 40, placeholder: "田中太郎", class: "form-control" %>
          <% @order.errors.full_messages_for(:name).each do |message| %>
            <div class="text-danger">*<%= message %></div>
          <% end %>
        </div>
    </div>
    <div class="col-mb-6 mx-auto mb-5">
        <div class="mb-3">
          <%= f.label :email, class: "form-label border-start border-primary border-4 ps-1" %>
          <%= f.text_field :email, size: 100, placeholder: "sample@example.com", class: "form-control" %>
          <% @order.errors.full_messages_for(:email).each do |message| %>
            <div class="text-danger">*<%= message %></div>
          <% end %>
        </div>
    </div>
    <div class="col-mb-6 mx-auto mb-5">
        <div class="mb-3">
          <%= f.label :telephone, class: "form-label border-start border-primary border-4 ps-1" %>
          <%= f.text_field :telephone, size: 40, placeholder: "00-1234-5678", class: "form-control" %>
          <% @order.errors.full_messages_for(:telephone).each do |message| %>
            <div class="text-danger">*<%= message %></div>
          <% end %>
        </div>
    </div>
    <div class="col-mb-6 mx-auto mb-5">
        <div class="mb-3">
          <%= f.label :delivery_address, class: "form-label border-start border-primary border-4 ps-1" %>
          <%= f.text_field :delivery_address, size: 40, placeholder: "お届け住所", class: "form-control" %>
          <% @order.errors.full_messages_for(:delivery_address).each do |message| %>
            <div class="text-danger">*<%= message %></div>
          <% end %>
        </div>
    </div>

    <div class="d-grid col-md-6 mx-auto">
      <%= f.button "確認画面へ", class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>
</div>